name: Build SmartDNS for OpenWrt x86_64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang flex bison g++ gawk \
            gcc-multilib g++-multilib gettext libncurses-dev libssl-dev \
            python3-distutils rsync unzip zlib1g-dev file wget

      - name: Download OpenWrt SDK (x86_64)
        run: |
          wget https://downloads.openwrt.org/releases/22.03.5/targets/x86/64/openwrt-sdk-22.03.5-x86-64_gcc-11.2.0_musl.Linux-x86_64.tar.xz
          tar -xf openwrt-sdk-*.tar.xz
          mv openwrt-sdk-* openwrt-sdk

      - name: Clone SmartDNS into SDK package directory
        run: |
          cd openwrt-sdk/package
          git clone https://github.com/${{ github.repository }} smartdns
          cd ../..

      - name: Build SmartDNS
        run: |
          cd openwrt-sdk
          echo "src-git packages https://git.openwrt.org/feed/packages.git" >> feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          make defconfig
          make package/smartdns/compile V=s -j$(nproc)

      - name: Upload .ipk package
        uses: actions/upload-artifact@v3
        with:
          name: smartdns-x86_64
          path: openwrt-sdk/bin/packages/x86_64/*/smartdns_*.ipk
