name: Build SmartDNS for OpenWrt x86_64 using SDK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex bison g++ gawk \
            gcc-multilib g++-multilib gettext libncurses-dev libssl-dev \
            python3-distutils rsync unzip zlib1g-dev file wget

      - name: Download OpenWrt SDK for x86_64
        run: |
          wget https://downloads.openwrt.org/releases/22.03.5/targets/x86/64/openwrt-sdk-22.03.5-x86-64_gcc-11.2.0_musl.Linux-x86_64.tar.xz
          tar -xf openwrt-sdk-*.tar.xz
          mv openwrt-sdk-* openwrt-sdk

      - name: Move SmartDNS Makefile into SDK package dir
        run: |
          mkdir -p openwrt-sdk/package/smartdns
          cp -r ./package/* openwrt-sdk/package/smartdns/

      - name: Compile SmartDNS .ipk
        run: |
          cd openwrt-sdk
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          make defconfig
          make package/smartdns/compile V=s -j$(nproc)

      - name: Upload compiled .ipk
        uses: actions/upload-artifact@v4
        with:
          name: smartdns-x86_64-ipk
          path: openwrt-sdk/bin/packages/x86_64/*/smartdns_*.ipk
