name: Build SmartDNS OpenWrt (official script)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y make g++ git unzip wget curl libtool \
            build-essential autoconf automake pkg-config \
            libssl-dev zlib1g-dev

      - name: Clone SmartDNS source
        run: |
          rm -rf package/src
          mkdir -p package/src
          git clone --depth=1 https://github.com/pymumu/smartdns package/src/smartdns

      - name: Run build-pkg.sh for x86_64
        run: |
          cd package
          chmod +x build-pkg.sh
          ./build-pkg.sh --platform openwrt --arch x86-64

      - name: List output files
        run: |
          echo "查找所有 .ipk 输出："
          find package/output -type f -name "*.ipk" || echo "❌ 没有找到 .ipk 文件"

      - name: Upload .ipk result (auto-detect)
        uses: actions/upload-artifact@v4
        with:
          name: smartdns-ipk
          path: |
            package/output/**/*.ipk
            output/**/*.ipk
